<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <Copyright>Copyright (c) 2026 MoriTeahouse (森之宿茶室)</Copyright>
    <Authors>MoriTeahouse</Authors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MatrixTea.Engine.MonoGame/MatrixTea.Engine.MonoGame.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
</Project>
