<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../MatrixTea.Engine.Core/MatrixTea.Engine.Core.csproj" /><ProjectReference Include="../MatrixTea.Engine.Packaging/MatrixTea.Engine.Packaging.csproj" /></ItemGroup>
</Project>
